### ISSUE TITLE
DuplicateCleanerPro@4.1.1: download via aria2 failed

### ISSUE THREAD

**Issue by zero617** [okibcn/ScoopMaster#2]
ERROR Download failed! (Error 1) An unknown error occurred
ERROR https://scoop.jtxiao.com/Duplicate_Cleaner_Pro-4.1.1.zip
    referer=https://scoop.jtxiao.com/
    dir=D:\Software\scoop\cache
    out=DuplicateCleanerPro#4.1.1#https_scoop.jtxiao.com_Duplicate_Cleaner_Pro-4.1.1.zip

ERROR & 'D:\Software\scoop\apps\aria2\current\aria2c.exe' --input-file='D:\Software\scoop\cache\DuplicateCleanerPro.txt' --user-agent='Scoop/1.0 (+http://scoop.sh/) PowerShell/7.3 (Windows NT 10.0; Win64; x64; Core)' --allow-overwrite=true --auto-file-renaming=false --retry-wait=3 --split=16 --max-connection-per-server=16 --min-split-size=1M --console-log-level=warn --enable-color=false --no-conf=true --follow-metalink=true --metalink-preferred-protocol=https --min-tls-version=TLSv1.2 --stop-with-process=38088 --continue --summary-interval=0 --auto-save-interval=1 --all-proxy='127.0.0.1:7890'

**Comment by okibcn** [comment]
The manifest comes from [this bucket](https://github.com/tac091/scoop-multi). Actually this is the [original manifest](https://github.com/tac091/scoop-multi/blob/main/bucket/DuplicateCleanerPro.json); and is dated Sep 14, 2021.

I am sorry the source was not working anymore. This bucket will soon be deprecated automatically. This is something Scoop is solving with the required autoupdate field.
