### ISSUE TITLE
ths-desktop@9.10.40_20220412: download via aria2 failed

### ISSUE THREAD

**Issue by cyberyoung** [okibcn/ScoopMaster#3]
` scoop install ths-desktop`

`ERROR Download failed! (Error 3) Resource was not found
ERROR http://resource.thsi.cn/download/THS_9.10.40_20220412.exe
    referer=http://resource.thsi.cn/download/
    dir=C:\Users\cyber\scoop\cache
    out=ths-desktop#9.10.40_20220412#http_resource.thsi.cn_download_THS_9.10.40_20220412.exe
`

**Comment by okibcn** [comment]
The source of the Manifest is this bucket: https://github.com/SayCV/scoop-cvp

Please open the issue there. The fix will be solved in this bucket within 30 minutes after the original bucket gets fixed.
