### ISSUE TITLE
riotimagetool@0.6: hash check failed

### ISSUE THREAD

**Issue by xerzo** [okibcn/ScoopMaster#5]
PS C:\Users\Xuiza> scoop install riotimagetool
Installing 'riotimagetool' (0.6) [64bit] from okibcn_ScoopMaster bucket
Starting download with aria2 ...
Download: Download Results:
Download: gid   |stat|avg speed  |path/URI
Download: ======+====+===========+=======================================================
Download: ef1ef7|OK  |    14MiB/s|C:/Users/Xuiza/scoop/cache/riotimagetool#0.6#https_dl-web.dropbox.com_s_rpi9v57y1yx4qpd_Riot.zip
Download: Status Legend:
Download: (OK):download completed.
Checking hash of Riot.zip ... ERROR Hash check failed!
App:         okibcn_ScoopMaster/riotimagetool
URL:         https://dl-web.dropbox.com/s/rpi9v57y1yx4qpd/Riot.zip
First bytes: 50 4B 03 04 14 00 00 00
Expected:    b17610ccb2612153b07db68ac2234d018cc67a160812a729d599e846e1138eb2
Actual:      202fc050b98279adaeb27bc89c0a934f49765069c8d28ac4604acce2d7bb9018

**Comment by okibcn** [comment]
The source bucket for that app is https://github.com/Jvcon/werkzeugeold

Please create an issue in that bucket. The fix will be propagated to ScoopMaster within 30 minutes after the owner of the original bucket fixes it.
