### ISSUE TITLE
Shovel's powershell command for changing update source

### ISSUE THREAD

**Issue by ErogeMaster225** [okibcn/ScoopMaster#8]
https://github.com/Ash258/Scoop-Core/blob/52fe1646d87ead40b642f112c3105c5aa54da3a5/CHANGELOG.md?plain=1#L274
In Shovel changelog it say they changed the filename from install.json to scoop-install.json so the powershell command in your README only works for Scoop but not Shovel. While the fix is simple (just replace install.json with scoop-install.json) it can cause a lot of confusion to many Shovel users wondering why it won't works.

**Comment by okibcn** [comment]
I am not familiar with this fork. Why using shovel when you can use the original? What are the benefits?

**Comment by ErogeMaster225** [comment]
> I am not familiar with this fork. Why using shovel when you can use the original? What are the benefits?
I moved to his fork because of the lack of contribution to the original scoop repo back then (you can find some issues on the repo asking if the project is being abandoned or "looking for maintainer"). He also implemented some requested feature in his fork.

**Comment by okibcn** [comment]
What are the exact additions? 

What I can see is the opposite. Shovel has been abandoned without any change in 2 years, while Scoop is being constantly maintained. So compatibility with a dead project is not an issue here.
